#!/usr/bin/env python3
import sys
import gi
import os
import shutil
import urllib.parse
from datetime import datetime
import getpass
import pathlib
import glob

# --- DÔLEŽITÉ IMPORTY ---
gi.require_version('Gtk', '4.0')
gi.require_version('Gio', '2.0')
gi.require_version('Adw', '1')
from gi.repository import Gtk, Gio, GObject, GLib, Adw

# --- KONFIGURÁCIA A MANUÁLNE SKENOVANIE ---

def get_trash_paths():
    paths = []
    
    HOME_TRASH = os.path.expanduser("~/.local/share/Trash")
    if os.path.isdir(HOME_TRASH):
        paths.append(HOME_TRASH)
    
    uid = os.getuid()
    user = getpass.getuser()
    
    media_dirs = glob.glob(f'/media/*/*') + glob.glob(f'/run/media/{user}/*')
    
    for mount_path in media_dirs:
        candidates = [
            os.path.join(mount_path, f".Trash-{uid}"),
            os.path.join(mount_path, ".Trash", str(uid)),
            os.path.join(mount_path, ".Trash")
        ]
        for c in candidates:
            if os.path.isdir(c):
                files_check = os.path.join(c, "files")
                if os.path.isdir(files_check) or os.path.lexists(files_check):
                    paths.append(c)
                
    final_paths = []
    for p in sorted(list(set(paths))):
        info_path = os.path.join(p, "info")
        files_path = os.path.join(p, "files")
        if os.path.isdir(info_path) and os.path.isdir(files_path):
             final_paths.append(p)
    
    return final_paths

# --- OBJEKT PRE POLOŽKU ---

class TrashItem(GObject.Object):
    __gtype_name__ = 'TrashItem'

    def __init__(self, trash_root, info_filename):
        super().__init__()
        self.trash_root = trash_root 
        
        self.info_file_path = os.path.join(trash_root, "info", info_filename)
        self.files_filename = info_filename[:-10] 
        self.data_file_path = os.path.join(trash_root, "files", self.files_filename)
        
        self.original_path = ""
        self.deletion_date = ""
        self.deletion_timestamp = None
        self.display_name = self.files_filename

        self._parse_info_file()

    def _parse_info_file(self):
        try:
            with open(self.info_file_path, 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            for line in lines:
                line = line.strip()
                if line.startswith("Path="):
                    raw_path = line[5:]
                    self.original_path = urllib.parse.unquote(raw_path)
                elif line.startswith("DeletionDate="):
                    raw_date = line[13:]
                    try:
                        dt = datetime.strptime(raw_date.split('.')[0], "%Y-%m-%dT%H:%M:%S")
                        self.deletion_timestamp = dt
                        self.deletion_date = dt.strftime("%d.%m.%Y %H:%M")
                    except:
                        self.deletion_date = raw_date
                        self.deletion_timestamp = datetime.min
        except Exception:
            self.deletion_timestamp = datetime.min
            pass 

    @GObject.Property(type=str)
    def name_prop(self):
        return self.display_name

    @GObject.Property(type=str)
    def location_prop(self):
        return self.original_path

    @GObject.Property(type=str)
    def date_prop(self):
        return self.deletion_date

# --- HLAVNÁ APLIKAČNÁ TRIEDA ---

class TrashApp(Adw.ApplicationWindow):
    def __init__(self, app):
        super().__init__(application=app, title="Môj Kôš (Kompletný)")
        self.set_default_size(900, 600)

        # Nastavenie tmavej témy podľa AdwStyleManager
        style_manager = Adw.StyleManager.get_default()
        style_manager.set_color_scheme(Adw.ColorScheme.PREFER_DARK)

        # Pridanie CSS pre zaoblené rohy
        self.setup_css()

        main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL, spacing=0)
        self.set_content(main_box)

         # --- TOOLBAR ---
        header_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        header_box.set_margin_top(10)
        header_box.set_margin_bottom(10)
        header_box.set_margin_start(10)
        header_box.set_margin_end(10)
        
        # Tlačidlá v strede
        center_box = Gtk.Box(orientation=Gtk.Orientation.HORIZONTAL, spacing=10)
        center_box.set_halign(Gtk.Align.CENTER)
        center_box.set_hexpand(True)
        
        self.btn_restore = Gtk.Button(label="Obnoviť vybrané")
        self.btn_restore.add_css_class("suggested-action")
        self.btn_restore.set_sensitive(False)
        self.btn_restore.connect("clicked", self.on_restore_clicked)
        center_box.append(self.btn_restore)

        self.btn_empty = Gtk.Button(label="Vyprázdniť kôš")
        self.btn_empty.connect("clicked", self.on_empty_clicked)
        center_box.append(self.btn_empty)
        
        header_box.append(center_box)
        
        # Tlačidlo na zatvorenie vpravo
        self.btn_close = Gtk.Button(icon_name="window-close-symbolic")
        self.btn_close.set_halign(Gtk.Align.END)
        self.btn_close.set_margin_start(10)
        self.btn_close.connect("clicked", lambda btn: self.close())
        header_box.append(self.btn_close)
        main_box.append(header_box)

        # --- ZOZNAM ---
        self.store = Gio.ListStore(item_type=TrashItem)
        
        self.store.connect("items-changed", self.on_store_items_changed)

        self.selection_model = Gtk.MultiSelection(model=self.store)
        self.selection_model.connect("selection-changed", self.on_selection_changed)

        self.column_view = Gtk.ColumnView(model=self.selection_model)
        self.column_view.set_show_row_separators(True)
        self.column_view.set_show_column_separators(True)

        self.add_column("Názov", "name_prop", expand=True)
        self.add_column("Pôvodné umiestnenie", "location_prop")
        self.add_column("Dátum zmazania", "date_prop")

        scrolled = Gtk.ScrolledWindow()
        scrolled.set_child(self.column_view)
        scrolled.set_vexpand(True)
        main_box.append(scrolled)

        self.load_trash_items()

    def setup_css(self):
        css = """
        @define-color dialog_bg_color @window_bg_color;
        @define-color dialog_fg_color @window_fg_color;

        window {
            border-radius: 18px;
        }
        """
        css_provider = Gtk.CssProvider()
        css_provider.load_from_data(css.encode())
        Gtk.StyleContext.add_provider_for_display(
            self.get_display(),
            css_provider,
            Gtk.STYLE_PROVIDER_PRIORITY_APPLICATION
        )

    def add_column(self, title, prop_name, expand=False):
        factory = Gtk.SignalListItemFactory()
        
        def setup_cb(factory, item):
            label = Gtk.Label()
            label.set_halign(Gtk.Align.START)
            label.set_margin_start(10)
            label.set_ellipsize(3)
            item.set_child(label)

        def bind_cb(factory, item):
            label = item.get_child()
            obj = item.get_item()
            if obj: 
                label.set_text(getattr(obj, prop_name))

        factory.connect("setup", setup_cb)
        factory.connect("bind", bind_cb)

        col = Gtk.ColumnViewColumn(title=title, factory=factory)
        if expand:
            col.set_expand(True)
        self.column_view.append_column(col)

    def load_trash_items(self):
        self.store.remove_all() 
        trash_paths = get_trash_paths()
        
        all_items = []
        
        for root in trash_paths:
            info_dir = os.path.join(root, "info")
            files_dir = os.path.join(root, "files")
                            
            try:
                info_files = [f for f in os.listdir(info_dir) if f.endswith(".trashinfo")]
                
                for filename in info_files:
                    data_filename = filename[:-10]
                    data_path = os.path.join(files_dir, data_filename)
                    
                    if os.path.lexists(data_path):
                        item = TrashItem(root, filename)
                        all_items.append(item)
            except OSError:
                pass 
        
        all_items.sort(key=lambda x: x.deletion_timestamp if x.deletion_timestamp else datetime.min, reverse=True)
        
        for item in all_items:
            self.store.append(item)
        
        self.update_buttons_state()

    def on_store_items_changed(self, store, position, removed, added):
        GLib.idle_add(self.update_buttons_state)

    def on_selection_changed(self, model, position, n_items):
        GLib.idle_add(self.update_buttons_state)

    def update_buttons_state(self):
        n_items = self.store.get_n_items()
        
        self.btn_empty.set_sensitive(n_items > 0)

        selection = self.selection_model.get_selection()
        has_selection = not selection.is_empty()
        self.btn_restore.set_sensitive(has_selection)

    def on_restore_clicked(self, btn):
        selected_items = []
        n_items = self.store.get_n_items()
        
        for i in range(n_items):
            if self.selection_model.is_selected(i):
                selected_items.append(self.store.get_item(i))

        if not selected_items:
            return

        for item in selected_items:
            try:
                src = item.data_file_path
                dst = item.original_path
                info = item.info_file_path
                
                if not os.path.lexists(src): 
                    continue

                dst_dir = os.path.dirname(dst)
                os.makedirs(dst_dir, exist_ok=True)
                
                if os.path.lexists(dst):
                    self.show_error(f"Súbor už existuje na cieľovom mieste:\n{dst}")
                    continue

                shutil.move(src, dst)
                
                if os.path.exists(info):
                    os.remove(info)

            except Exception as e:
                self.show_error(f"Chyba pri obnove {item.display_name}:\n{e}")

        self.load_trash_items()

    def on_empty_clicked(self, btn):
        n_items = self.store.get_n_items()
        if n_items == 0:
            return
            
        # Adw.AlertDialog sa kreslí priamo v okne, takže preberá jeho tému
        dialog = Adw.AlertDialog.new(
            "Vyprázdniť kôš",
            "Naozaj chcete vyprázdniť kôš? Položky budú trvalo zmazané."
        )
        dialog.add_response("cancel", "Zrušiť")
        dialog.add_response("empty", "Vyprázdniť")
        dialog.set_response_appearance("empty", Adw.ResponseAppearance.DESTRUCTIVE)
        dialog.set_default_response("cancel")
        dialog.set_close_response("cancel")
        dialog.choose(self, None, self.on_empty_dialog_response)

    def on_empty_dialog_response(self, dialog, result):
        if dialog.choose_finish(result) == "empty":
            self.perform_empty()

    def perform_empty(self):
        n_items = self.store.get_n_items()
        items = [self.store.get_item(i) for i in range(n_items)]
        
        for item in items:
            try:
                if os.path.lexists(item.data_file_path):
                    if os.path.islink(item.data_file_path):
                        os.unlink(item.data_file_path)
                    elif os.path.isdir(item.data_file_path):
                        shutil.rmtree(item.data_file_path)
                    else:
                        os.remove(item.data_file_path)
                
                if os.path.exists(item.info_file_path):
                    os.remove(item.info_file_path)
            except Exception as e:
                print(f"Chyba pri mazaní {item.display_name}: {e}")
        
        self.load_trash_items()

    def show_error(self, msg):
        dialog = Adw.AlertDialog.new("Chyba operácie", msg)
        dialog.add_response("ok", "OK")
        dialog.present(self)

# --- SPÚŠŤACIA TRIEDA ---
class MyApp(Adw.Application):
    def __init__(self):
        super().__init__(application_id="com.example.finaltrashmanager")

    def do_activate(self):
        win = TrashApp(self)
        win.present()

if __name__ == "__main__":
    app = MyApp()
    exit_status = app.run(sys.argv)
    sys.exit(exit_status)